export const SEND_CONTACT_FORM_START = "SEND_CONTACT_FORM_START";
export const SEND_CONTACT_FORM_SUCCESS = "SEND_CONTACT_FORM_SUCCESS";
export const SEND_CONTACT_FORM_FAIL = "SEND_CONTACT_FORM_FAIL";
